# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.77.0
    hooks:
      - id: terraform_fmt
      - id: terraform_validate
        args:
          - --init-args=-backend=false
          - --init-args=-lockfile=readonly
      - id: terraform_tflint
        args:
          - --args=--module
      - id: terraform_tfsec
        args:
          - --args=--minimum-severity HIGH --exclude-downloaded-modules
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-merge-conflict
