name: deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          registry-url: 'https://npm.pkg.github.com'

      - run: make test build

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::053041861227:role/github-s3-access-eu-west-1
          role-session-name: GitHubActions
          aws-region: eu-west-1

      - name: Copy files to production with the AWS CLI
        run: |
          aws s3 sync target/ s3://buzzhub-lambda-source-053041861227-eu-west-1